language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install requests 
  - pip install pytest requests_mock mock
  - pip install setuptools
script:
  - python -m pytest -vv
  - python setup.py install
