language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install requests 
  - pip install pytest requests_mock mock pytest-cov codecov
  - pip install setuptools

script:
  - python -m pytest -vv --cov=./
  - python setup.py install

after_success:
  - codecov
